# Define image
default:
  image: node:16.15.0-alpine

  before_script:
    - yarn install

stages:
  - test

.test_stage: &test_stage
  stage: test
  tags:
    - shared
  artifacts:
    when: always
    paths:
      - ./coverage/spec.xml
    reports:
      junit: ./coverage/spec.xml
  script:
    - yarn test

# Run test
test:
  <<: *test_stage
  environment:
    name: DEV
  variables:
    NODE_ENV: test
    PORT: 1337
